import img1 from "../../assets/Home/Industries/unsplash_jjhvyxm34nY.png";
import { RiCheckboxMultipleLine } from "react-icons/ri";
import { AiOutlineHeart } from "react-icons/ai";

export const Data = [
  {
    id: 1,
    optionName: ["5+ Years Of Average", "Experience"],
    optionLogo: <AiOutlineHeart />,
    head: "5+ Years Of Average Experience",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
        { id: 1, name: "Strategic Consulting" },
        { id: 2, name: "Intellectual property-based mobile technology solutions", },
        { id: 3, name: "Industry-focused mobility solutions" },
        { id: 4, name: "Enterprise platforms" },
        { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
        { id: 6, name: "Mobile testing service" },
    ],
  },
  {
    id: 2,
    optionName: ["Free No Obligation", "Quote"],
    optionLogo: <RiCheckboxMultipleLine />,
    head: "Free No Obligation Quote",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
        { id: 1, name: "Strategic Consulting" },
        { id: 2, name: "Intellectual property-based mobile technology solutions", },
        { id: 3, name: "Industry-focused mobility solutions" },
        { id: 4, name: "Enterprise platforms" },
        { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
        { id: 6, name: "Mobile testing service" },
    ],
  },
  {
    id: 3,
    optionName: ["Transparency Is", "Guaranteed"],
    optionLogo: <RiCheckboxMultipleLine />,
    head: "Transparency Is Guaranteed",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
        { id: 1, name: "Strategic Consulting" },
        { id: 2, name: "Intellectual property-based mobile technology solutions", },
        { id: 3, name: "Industry-focused mobility solutions" },
        { id: 4, name: "Enterprise platforms" },
        { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
        { id: 6, name: "Mobile testing service" },
    ],
  },
  {
    id: 4,
    optionName: ["Enterprice", "Transparency"],
    optionLogo: <RiCheckboxMultipleLine />,
    head: "Integrity & Transparency",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
        { id: 1, name: "Strategic Consulting" },
        { id: 2, name: "Intellectual property-based mobile technology solutions", },
        { id: 3, name: "Industry-focused mobility solutions" },
        { id: 4, name: "Enterprise platforms" },
        { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
        { id: 6, name: "Mobile testing service" },
    ],
  },
  {
    id: 5,
    optionName: ["Hassle-free Project", "Management"],
    optionLogo: <RiCheckboxMultipleLine />,
    head: "Hassle-free Project Management",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
        { id: 1, name: "Strategic Consulting" },
        { id: 2, name: "Intellectual property-based mobile technology solutions", },
        { id: 3, name: "Industry-focused mobility solutions" },
        { id: 4, name: "Enterprise platforms" },
        { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
        { id: 6, name: "Mobile testing service" },
    ],
  },

  {
    id: 6,
    optionName: ["Free No Obligation", "Quote"],
    optionLogo: <RiCheckboxMultipleLine />,
    head: "Free No Obligation Quote",
    text: "Our experienced Android app developers are experts with Android development frameworks.",
    image: img1,
    services: [
      { id: 1, name: "Strategic Consulting" },
      { id: 2, name: "Intellectual property-based mobile technology solutions", },
      { id: 3, name: "Industry-focused mobility solutions" },
      { id: 4, name: "Enterprise platforms" },
      { id: 5, name: "Custom apps connected to SAP, Salesforce, CRM and other ERP’s", },
      { id: 6, name: "Mobile testing service" },
    ],
  },
];
